//------------------------------------------------------------------------------
// <auto-generated>
//     โค้ดนี้ถูกสร้างขึ้นโดยเครื่องมือ (Tool)
//     รุ่นรันไทม์: 4.0.30319.42000
//
//     การแก้ไขไฟล์นี้อาจทำให้เกิดพฤติกรรมที่ไม่ถูกต้องและจะสูญหายไปหาก
//     มีการสร้างโค้ดขึ้นมาใหม่ในครั้งถัดไป
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Made And Checked By DELTA SYNTH & Gemini AI
 * Original Author: Microsoft Resource Designer & OpenUtau Team
 */

namespace OpenUtau.Resources {
    using System;
    
    /// <summary>
    ///   คลาสทรัพยากร (Resource Class) ที่มีการระบุชนิดข้อมูลอย่างชัดเจน 
    ///   สำหรับการค้นหาข้อความที่แปลแล้ว (Localized Strings) และข้อมูลอื่นๆ
    /// </summary>
    // คลาสนี้ถูกสร้างขึ้นโดยเครื่องมือ StronglyTypedResourceBuilder โดยอัตโนมัติ
    // ผ่านเครื่องมืออย่าง ResGen หรือ Visual Studio
    // หากต้องการเพิ่มหรือลบสมาชิก ให้แก้ไขไฟล์ .ResX แล้วรัน ResGen ใหม่ด้วยตัวเลือก /str
    // หรือทำการสร้างโปรเจกต์ใน Visual Studio ใหม่อีกครั้ง
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   คืนค่าอินสแตนซ์ ResourceManager ที่แคชไว้ซึ่งใช้งานโดยคลาสนี้
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtau.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   เขียนทับคุณสมบัติ CurrentUICulture ของเธรดปัจจุบัน สำหรับการค้นหาทรัพยากรทั้งหมด
        ///   โดยใช้คลาสทรัพยากรที่มีการระบุชนิดข้อมูลอย่างชัดเจนนี้
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ค้นหาทรัพยากรที่แปลแล้วในรูปแบบ System.Byte[]
        ///   (สำหรับเครื่องมือ Unzipper ในการแตกไฟล์ Voicebank)
        /// </summary>
        internal static byte[] Unzipper {
            get {
                object obj = ResourceManager.GetObject("Unzipper", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
