//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtau.Core.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtau.Core.Api.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] arpasing_template {
            get {
                object obj = ResourceManager.GetObject("arpasing_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;;; # CMUdict  --  Major Version: 0.07
        ///;;; 
        ///;;; # $HeadURL$
        ///;;; # $Date::                                                   $:
        ///;;; # $Id::                                                     $:
        ///;;; # $Rev::                                                    $: 
        ///;;; # $Author::                                                 $:
        ///;;;
        ///;;; #
        ///;;; # ========================================================================
        ///;;; # Copyright (C) 1993-2015 Carnegie Mellon University. All rights reserved.
        ///;;;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cmudict_0_7b {
            get {
                return ResourceManager.GetString("cmudict_0_7b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA	vowel
        ///AE	vowel
        ///AH	vowel
        ///AO	vowel
        ///AW	vowel
        ///AY	vowel
        ///B	stop
        ///CH	affricate
        ///D	stop
        ///DH	fricative
        ///EH	vowel
        ///ER	vowel
        ///EY	vowel
        ///F	fricative
        ///G	stop
        ///HH	aspirate
        ///IH	vowel
        ///IY	vowel
        ///JH	affricate
        ///K	stop
        ///L	liquid
        ///M	nasal
        ///N	nasal
        ///NG	nasal
        ///OW	vowel
        ///OY	vowel
        ///P	stop
        ///R	liquid
        ///S	fricative
        ///SH	fricative
        ///T	stop
        ///TH	fricative
        ///UH	vowel
        ///UW	vowel
        ///V	fricative
        ///W	semivowel
        ///Y	semivowel
        ///Z	fricative
        ///ZH	fricative
        ///.
        /// </summary>
        public static string cmudict_0_7b_phones {
            get {
                return ResourceManager.GetString("cmudict_0_7b_phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA
        ///AA0
        ///AA1
        ///AA2
        ///AE
        ///AE0
        ///AE1
        ///AE2
        ///AH
        ///AH0
        ///AH1
        ///AH2
        ///AO
        ///AO0
        ///AO1
        ///AO2
        ///AW
        ///AW0
        ///AW1
        ///AW2
        ///AY
        ///AY0
        ///AY1
        ///AY2
        ///B
        ///CH
        ///D
        ///DH
        ///EH
        ///EH0
        ///EH1
        ///EH2
        ///ER
        ///ER0
        ///ER1
        ///ER2
        ///EY
        ///EY0
        ///EY1
        ///EY2
        ///F
        ///G
        ///HH
        ///IH
        ///IH0
        ///IH1
        ///IH2
        ///IY
        ///IY0
        ///IY1
        ///IY2
        ///JH
        ///K
        ///L
        ///M
        ///N
        ///NG
        ///OW
        ///OW0
        ///OW1
        ///OW2
        ///OY
        ///OY0
        ///OY1
        ///OY2
        ///P
        ///R
        ///S
        ///SH
        ///T
        ///TH
        ///UH
        ///UH0
        ///UH1
        ///UH2
        ///UW
        ///UW0
        ///UW1
        ///UW2
        ///V
        ///W
        ///Y
        ///Z
        ///ZH
        ///.
        /// </summary>
        public static string cmudict_0_7b_symbols {
            get {
                return ResourceManager.GetString("cmudict_0_7b_symbols", resourceCulture);
            }
        }
    }
}
