name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
body:
  - type: markdown
    attributes:
      value: |
        GitHub issues are for reporting bugs and crashes. Vague help requests are not efficiently handled here.
        For help request please read [Getting-Started](https://github.com/stakira/OpenUtau/wiki/Getting-Started) and [FAQ](https://github.com/stakira/OpenUtau/wiki/FAQ) and other wiki pages first.
        If dealing with version 0.1.549 or higher, your issue may be fixed by installing [the .NET 8 runtime](https://dotnet.microsoft.com/en-us/download/dotnet/8.0).
        If still not resolved, help requests are better handled in the Discord server or QQ group.
  - type: checkboxes
    attributes:
      label: Acknowledgement
      options:
        - label: I have read Getting-Started and FAQ
          required: true
        - label: If dealing with version 0.1.549 or higher, you have installed the .NET 8 runtime
          required: true
  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: >
        Please provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Explains how to reproduce the bug
      description: |
        Explains how to make the bug happen again.
        Explains what's the voicebank used, where to get it.
        Share the ust or ustx file if you could. Or you could isolate the issue in a small file.
      placeholder: |
        Example:
        1. Go to '...'
        2. Click on '...'
        3. See error '...'
        4. Voicebank is '...'
        5. Attach ustx
    validations:
      required: true
  - type: input
    attributes:
      label: OS & Version
      description: >
        Example: Windows 7, Windows 10, macOS 10.14, macOS 11.16, Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        Find the log corresponding to the bug and attach it here.
        Log files are under Logs folder.
        When in doubt, delete all log files, reproduce the bug, and attach the new log file.
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing!
