using System;
using System.IO;

using OpenUtau.Api;
using OpenUtau.Core.Ustx;
using OpenUtau.Core.Vogen;
using System.Collections.Generic;
using Serilog;

namespace OpenUtau.Core.DiffSinger {
    [Phonemizer("DiffSinger Chinese Mandarin Phonemizer", "DIFFS ZH", language: "ZH")]
    public class DiffsingerMandarinPhonemizer : VogenMandarinPhonemizer {
        USinger singer;
        Dictionary<string, Tuple<string, string>> phoneDict = new Dictionary<string, Tuple<string, string>>();

        //Initialization
        public override void SetSinger(USinger singer) {
            if (this.singer == singer) {
                return;
            }
            this.singer = singer;
            if (this.singer == null) {
                return;
            }
            //import dsdict.txt (pinyin to phonemes)
            try {
                phoneDict.Clear();
                HashSet<string> phonemesSet = new HashSet<string> { "SP", "AP" };
                string path = Path.Combine(singer.Location, "dsdict.txt");
                phoneDict.Add("AP", new Tuple<string, string>("", "AP"));
                phoneDict.Add("SP", new Tuple<string, string>("", "SP"));
                foreach (string line in File.ReadLines(path, singer.TextFileEncoding)) {
                    string[] elements = line.Split("\t");
                    elements[1] = elements[1].Trim();
                    if (elements[1].Contains(" ")) {//Consonant + Vowel
                        string[] phones = elements[1].Split(" ");
                        phoneDict.Add(elements[0].Trim(), new Tuple<string, string>(phones[0], phones[1]));
                        phonemesSet.Add(phones[0]);
                        phonemesSet.Add(phones[1]);
                    } else {//Vowel only
                        phoneDict.Add(elements[0].Trim(), new Tuple<string, string>("", elements[1]));
                        phonemesSet.Add(elements[1]);
                    } 
                }
            }
            catch (Exception e) {
                Log.Error(e, "failed to load dsdict.txt");
            }
        }

        public override void SetUp(Note[][] groups) {
            if (groups.Length == 0) {
                return;
            }
            //Hanzi to pinyin
            BaseChinesePhonemizer.RomanizeNotes(groups);
            base.SetUp(groups);
        }

        public override Result Process(Note[] notes, Note? prev, Note? next, Note? prevNeighbour, Note? nextNeighbour, Note[] prevs) {
            string lyric = notes[0].lyric;
            var phones = phoneDict[lyric];
            if (phones.Item1 == "") {//Vowel only
                return MakeSimpleResult(phones.Item2);
            }
            //Use consonant duration generated by vogen
            Result VogenResult = base.Process(notes, prev, next, prevNeighbour, nextNeighbour, prevs);
            //If the consonant is too short, there is no need to handle it here 
            //because openutau has a built-in protection mechanism
            int consonantPos = VogenResult.phonemes[0].position;
            //Consonant shouldn't be longer than 2/3 of the previous note
            if (prevNeighbour != null) {
                consonantPos = Math.Max(consonantPos, -prevNeighbour.Value.duration * 2 / 3);
            }
            return new Result {
                phonemes = new Phoneme[] {
                    new Phoneme {phoneme = phones.Item1, position = consonantPos},
                    new Phoneme {phoneme = phones.Item2, position = 0}
                },
            };
        }
    }
}
